# Generated by Django 4.1.2 on 2022-10-13 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepts',
            name='adate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accepts',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.orders'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='desc',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='confirms',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='confirms',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.orders'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cid',
            field=models.CharField(default='', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.orders'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.customers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='odate',
            field=models.DateTimeField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.CharField(default='', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.CharField(default='', max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='send',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.orders'),
        ),
        migrations.AlterField(
            model_name='send',
            name='sdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.orders'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='tdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
