# Generated by Django 4.1.2 on 2022-10-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0002_rename_amount_orderdetails_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='12345678', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='accepts',
            name='adate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='confirms',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='odate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='send',
            name='sdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='tdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='confirms',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.employees'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.employees'),
        ),
    ]
