# Generated by Django 4.1.2 on 2022-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0003_employees_rename_amount_orderdetails_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.FloatField(default=0.0),
        ),

    ]
