# Generated by Django 4.1.2 on 2022-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0004_customers_password_orderdetails_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='price',
            new_name='oprice',
        ),
    ]
