# Generated by Django 4.1.2 on 2022-10-16 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0005_rename_price_orderdetails_oprice_customers_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='employee',
        ),
        migrations.AddField(
            model_name='accepts',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.employees'),
        ),
        migrations.AddField(
            model_name='send',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.employees'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='bill',
            field=models.ImageField(default='', upload_to='static/bill/'),
        ),
    ]
