# Generated by Django 4.1.2 on 2022-10-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0006_remove_transfers_employee_accepts_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=200)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.orders')),
            ],
        ),
    ]
