# Generated by Django 4.1.2 on 2022-10-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0008_customers_password_products_picture_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='reject',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.employees'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='bill',
            field=models.ImageField(default='', upload_to='static/bills/'),
        ),
    ]
