# Generated by Django 4.1.2 on 2022-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0009_customers_password_products_picture_reject_employee_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='employees',
            name='birthdate',
            field=models.DateField(default=None),
        ),

    ]
